# Generated by Django 3.2.7 on 2021-09-29 09:58

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imae',
            field=models.FileField(null=True, upload_to=articles.models.picture_image),
        ),
    ]
